export const farmAbi = [
  { inputs: [{ name: "_stakingToken", type: "address" }, { name: "_allocPoint", type: "uint256" }], name: "addPool", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_pid", type: "uint256" }], name: "claimReward", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_pid", type: "uint256" }, { name: "_amount", type: "uint256" }], name: "deposit", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_pid", type: "uint256" }], name: "emergencyWithdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_pid", type: "uint256" }, { name: "_allocPoint", type: "uint256" }], name: "setAllocPoint", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_rewardPerBlock", type: "uint256" }], name: "setRewardPerBlock", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_rewardToken", type: "address" }], name: "setRewardToken", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_startBlock", type: "uint256" }], name: "setStartBlock", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_pid", type: "uint256" }], name: "updatePool", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_pid", type: "uint256" }, { name: "_amount", type: "uint256" }], name: "withdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "owner", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "_pid", type: "uint256" }, { name: "_user", type: "address" }], name: "pendingReward", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "poolInfo",
    outputs: [
      { name: "stakingToken", type: "address" },
      { name: "allocPoint", type: "uint256" },
      { name: "lastRewardBlock", type: "uint256" },
      { name: "accRewardPerShare", type: "uint256" },
      { name: "totalStaked", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "poolLength", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "rewardPerBlock", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "rewardToken", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "startBlock", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalAllocPoint", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    name: "userInfo",
    outputs: [
      { name: "amount", type: "uint256" },
      { name: "rewardDebt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;